apiVersion: v1
kind: Service
metadata:
  name: feedback-backend
  labels:
    app: feedback-backend
spec:
  selector:
    app: feedback-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP 