name: Deploying

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Frontend
      run: docker build -t arpitsrivastava529/feedback-system-frontend:latest ./frontend
    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Push Frontend
      run: docker push arpitsrivastava529/feedback-system-frontend:latest

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Backend
      run: docker build -t arpitsrivastava529/feedback-system-backend:latest ./backend
    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Push Backend
      run: docker push arpitsrivastava529/feedback-system-backend:latest